webtalk_init -webtalk_dir /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.sim/sim_1/behav/xsim/xsim.dir/match_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Mar 31 17:49:04 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2d59b721-f4ce-4f53-bd51-238e80b9887d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "354a32f9f7984ff1a822cbbe4d747ebf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Pentium(R) CPU G630 @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2693.856 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1300 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "128748_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1394526497 -regid "" -xml /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.sim/sim_1/behav/xsim/xsim.dir/match_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.sim/sim_1/behav/xsim/xsim.dir/match_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.sim/sim_1/behav/xsim/xsim.dir/match_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
