# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/bd/PLL_phase/ip/PLL_phase_clk_wiz_0_0/PLL_phase_clk_wiz_0_0.xci
# IP: The module: 'PLL_phase_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/bd/PLL_phase/ip/PLL_phase_clk_wiz_0_0/PLL_phase_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_phase_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/bd/PLL_phase/ip/PLL_phase_clk_wiz_0_0/PLL_phase_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_phase_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/bd/PLL_phase/ip/PLL_phase_clk_wiz_0_0/PLL_phase_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_phase_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/bd/PLL_phase/ip/PLL_phase_clk_wiz_0_0/PLL_phase_clk_wiz_0_0.xci
# IP: The module: 'PLL_phase_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/bd/PLL_phase/ip/PLL_phase_clk_wiz_0_0/PLL_phase_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_phase_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/bd/PLL_phase/ip/PLL_phase_clk_wiz_0_0/PLL_phase_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_phase_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/bd/PLL_phase/ip/PLL_phase_clk_wiz_0_0/PLL_phase_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_phase_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
