# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/vivado-essentials/xillydemo.xdc

# Block Designs: bd/PLL_phase/PLL_phase.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLL_phase || ORIG_REF_NAME==PLL_phase} -quiet] -quiet

# IP: bd/PLL_phase/ip/PLL_phase_clk_wiz_0_0/PLL_phase_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLL_phase_clk_wiz_0_0 || ORIG_REF_NAME==PLL_phase_clk_wiz_0_0} -quiet] -quiet

# IP: bd/PLL_phase/ip/PLL_phase_xlconcat_0_0/PLL_phase_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLL_phase_xlconcat_0_0 || ORIG_REF_NAME==PLL_phase_xlconcat_0_0} -quiet] -quiet

# XDC: bd/PLL_phase/PLL_phase_ooc.xdc
