# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.cache/wt [current_project]
set_property parent.project_path /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/imports/vhdl/10bitBuffer.vhd
  /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/imports/vhdl/DDRblock.vhd
  /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/imports/vhdl/DDRlatch.vhd
  /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/imports/vhdl/DDRshift.vhd
  /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/imports/vhdl/DFF.vhd
  /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/bd/PLL_phase/hdl/PLL_phase_wrapper.vhd
  /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/imports/vhdl/interface.vhd
  /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/imports/vhdl/byteBuffer.vhd
  /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/imports/vhdl/bit40shift.vhd
  /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/imports/vhdl/add.vhd
  /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/new/gap_counter.vhd
  /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/new/match.vhd
}
add_files /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/bd/PLL_phase/PLL_phase.bd
set_property used_in_implementation false [get_files -all /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/bd/PLL_phase/ip/PLL_phase_clk_wiz_0_0/PLL_phase_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/bd/PLL_phase/ip/PLL_phase_clk_wiz_0_0/PLL_phase_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/bd/PLL_phase/ip/PLL_phase_clk_wiz_0_0/PLL_phase_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/sources_1/bd/PLL_phase/PLL_phase_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/constrs_1/imports/vivado-essentials/xillydemo.xdc
set_property used_in_implementation false [get_files /home/eaglesat/Documents/plugsin/plugsin_PL/plugsin_PL.srcs/constrs_1/imports/vivado-essentials/xillydemo.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top interface -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef interface.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file interface_utilization_synth.rpt -pb interface_utilization_synth.pb"
